INSERT INTO SPORTS_MATCH_CRSTAT
(BASE_DE, BASE_YEAR, BASE_MT, BASE_DAY, CTPRVN_CD, CTPRVN_NM, SPORTS_MATCH_CO, KLEA_MATCH_CO, KBO_MATCH_CO, KBL_MATCH_CO, WKBL_MATCH_CO, KOVO_MATCH_CO)
SELECT
    BASE_DE
    , BASE_YEAR
    , BASE_MT
    , BASE_DAY
    , CTPRVN_CD
    , (SELECT CTPRVN_NM FROM kcisa.CTPRVN_INFO AS C WHERE C.CTPRVN_CD = S.CTPRVN_CD) AS CTPRVN_NM
    , SPORTS_MATCH_CO
    , KLEA_MATCH_CO
    , KBO_MATCH_CO
    , KBL_MATCH_CO
    , WKBL_MATCH_CO
    , KOVO_MATCH_CO
FROM colct_sports_viewng_info AS S
WHERE BASE_DE = ?
UNION ALL
SELECT
    BASE_DE
    ,MAX(BASE_YEAR) as BASE_YEAR
    , MAX(BASE_MT) as BASE_MT
    , MAX(BASE_DAY) as BASE_DAY
    , '00' AS CTPRVN_CD
    , '전국' AS CTPRVN_NM
    , SUM(SPORTS_MATCH_CO) AS SPORTS_MATCH_CO
    , SUM(KLEA_MATCH_CO) AS KLEA_MATCH_CO
    , SUM(KBO_MATCH_CO) AS KBO_MATCH_CO
    , SUM(KBL_MATCH_CO) AS KBL_MATCH_CO
    , SUM(WKBL_MATCH_CO) AS WKBL_MATCH_CO
    , SUM(KOVO_MATCH_CO) AS KOVO_MATCH_CO
FROM colct_sports_viewng_info AS S
WHERE BASE_DE = ?
GROUP BY BASE_DE
ORDER BY 1, 5
